package com.google.android.gms.ads.internal.config;

import android.content.Context;
import android.text.TextUtils;
import com.android.volley.toolbox.ImageRequest;
import com.google.android.gms.ads.internal.client.c;
import com.google.android.gms.ads.internal.flag.a;
import com.google.android.gms.ads.internal.flag.d;
import com.google.android.gms.ads.internal.flag.e;
import com.google.android.gms.ads.internal.flag.f;
import com.google.android.gms.ads.internal.util.r;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

/* compiled from: :com.google.android.gms@201216073@20.12.16 (080306-306753009) */
public final class n {
    public static final f a = f.a("gads:msa:experiments:enabled", (Boolean) false);
    public static final a b = d.a;
    public static final f c = f.a("gads:gestures:errorlogging:enabled", (Boolean) false);
    public static final f d = f.a("gads:gestures:task_timeout", 2000);
    public static final f e = f.a("gads:gestures:fpi:enabled", (Boolean) false);
    public static final f f = f.a("gads:gestures:inthex:enabled", (Boolean) false);
    public static final f g = f.a("gads:gestures:hpk:enabled", (Boolean) true);
    public static final f h = f.a("gads:gestures:pk", "");
    public static final f i = f.a("gads:gestures:bs:enabled", (Boolean) true);
    public static final f j = f.a("gads:gestures:check_initialization_thread:enabled", (Boolean) false);
    public static final f k = f.a("gads:gestures:get_query_in_non_ui_thread:enabled", (Boolean) true);
    public static final f l = f.a("gads:gestures:pds:enabled", (Boolean) true);
    public static final f m = f.a("gads:gestures:las:enabled", (Boolean) false);
    public static final f n = f.a("gads:gestures:ns:enabled", (Boolean) true);

    static {
        f.a("gads:sdk_core_location:client:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
        f.a("gads:active_view_location:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
        int i2 = e.a;
        f.a("gads:http_url_connection_factory:timeout_millis", 10000);
        f.a("gads:video_exo_player:version", "3");
        f.a("gads:video_exo_player:connect_timeout", 8000);
        f.a("gads:video_exo_player:read_timeout", 8000);
        f.a("gads:video_exo_player:loading_check_interval", 1048576);
        f.a("gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
        f.a("gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
        f.a("gads:video_exo_player_socket_receive_buffer_size", 0);
        f.a("gads:video_exo_player:precache_exceptions", "");
        f.a("gads:video_exo_player:min_retry_count", -1);
        f.a("gads:video_stream_cache:limit_count", 5);
        f.a("gads:video_stream_cache:limit_space", 8388608);
        f.a("gads:video_stream_exo_cache:buffer_size", 8388608);
        f.a("gads:video_stream_cache:limit_time_sec", 300);
        f.a("gads:video_stream_cache:notify_interval_millis", 125);
        f.a("gads:video_stream_cache:connect_timeout_millis", 10000);
        f.a("gads:video:metric_frame_hash_times", "");
        f.a("gads:video:metric_frame_hash_time_leniency", 500);
        f.a("gads:video:force_watermark", (Boolean) false);
        f.a("gads:video:surface_update_min_spacing_ms", 1000);
        f.a("gads:video:spinner:enabled", (Boolean) false);
        f.a("gads:video:spinner:scale", 4);
        f.a("gads:video:spinner:jank_threshold_ms", 50);
        f.a("gads:video:aggressive_media_codec_release", (Boolean) false);
        f.a("gads:memory_bundle:debug_info", (Boolean) false);
        f.a("gads:video:codec_query_mime_types", "");
        f.a("gads:video:codec_query_minimum_version", 16);
        f.a("gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_banner.js");
        f.a("gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_expanded_banner.js");
        f.a("gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_interstitial.js");
        f.a("gad:mraid:version", "3.0");
        f.a("gads:mraid:expanded_interstitial_fix", (Boolean) false);
        f.a("gads:mraid:initial_size_fallback", (Boolean) false);
        f.a("gads:content_vertical_fingerprint_number", 100);
        f.a("gads:content_vertical_fingerprint_bits", 23);
        f.a("gads:content_vertical_fingerprint_ngram", 3);
        f.a("gads:content_fetch_view_tag_id", "googlebot");
        f.a("gads:content_fetch_exclude_view_tag", "none");
        f.a("gads:content_fetch_disable_get_title_from_webview", (Boolean) false);
        f.a("gads:content_fetch_enable_new_content_score", (Boolean) false);
        f.a("gads:content_fetch_enable_serve_once", (Boolean) false);
        f.a("gads:sai:enabled", (Boolean) true);
        f.a("gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
        f.a("gads:sai:impression_ping_schema_v2", "^[^?]*(/adview|/pcs/view).*");
        f.a("gads:sai:using_macro:enabled", (Boolean) false);
        f.a("gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
        f.a("gads:sai:timeout_ms", -1);
        f.a("gads:sai:scion_thread_pool_size", 5);
        f.a("gads:sai:app_measurement_enabled3", (Boolean) false);
        f.a("gads:sai:app_measurement_min_client_dynamite_version", 20290);
        f.a("gads:sai:force_through_reflection", (Boolean) true);
        f.a("gads:sai:gmscore_availability_check_disabled", (Boolean) false);
        f.a("gads:sai:logging_disabled_for_drx", (Boolean) false);
        f.a("gads:sai:inject_firebase_proxy", (Boolean) false);
        f.a("gads:sai:app_measurement_npa_enabled", (Boolean) false);
        f.a("gads:interstitial:app_must_be_foreground:enabled", (Boolean) false);
        f.a("gads:interstitial:foreground_report:enabled", (Boolean) false);
        f.a("gads:webview:error_web_response:enabled", (Boolean) false);
        f.a("gads:webview:pause_interstitial:enabled", (Boolean) true);
        f.a("gads:rsku:webviewgone:kill_process:enabled", (Boolean) false);
        f.a("gads:webviewgone:kill_process:enabled", (Boolean) false);
        f.a("gads:rsku:webviewgone:new_onshow:enabled", (Boolean) true);
        f.a("gads:webviewgone:new_onshow:enabled", (Boolean) false);
        f.a("gads:webview:pause_resume:enabled", (Boolean) true);
        f.a("gads:new_rewarded_ad:enabled", (Boolean) true);
        f.a("gads:rewarded:adapter_initialization_enabled", (Boolean) false);
        f.a("gads:rewarded:adapter_timeout_ms", 20000);
        f.a("gads:rewarded:ad_metadata_enabled", (Boolean) false);
        f.a("gads:rewarded:ssv_custom_data_enabled", (Boolean) true);
        f.a("gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
        f.a("gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
        f.a("gads:adid_values_in_adrequest:enabled", (Boolean) false);
        f.a("gads:adid_values_in_adrequest:timeout", 2000);
        f.a("gads:disable_adid_values_in_ms", (Boolean) false);
        f.a("gads:ad_overlay:delay_page_close_timeout_ms", 5000);
        f.a("gads:custom_close_blocking:enabled", (Boolean) false);
        f.a("gads:disabling_closable_area:enabled", (Boolean) false);
        f.a("gads:use_system_ui_for_fullscreen:enabled", (Boolean) false);
        f.a("gads:ad_overlay:collect_cutout_info:enabled", (Boolean) false);
        f.a("gads:impression_optimization_enabled", (Boolean) false);
        f.a("gads:banner_ad_pool:schema", "customTargeting");
        f.a("gads:banner_ad_pool:max_queues", 3);
        f.a("gads:banner_ad_pool:max_pools", 3);
        f.a("gads:delay_banner_renderer:enabled", (Boolean) true);
        f.a("gads:interstitial_ad_pool:enabled", (Boolean) false);
        f.a("gads:interstitial_ad_pool:enabled_for_rewarded", (Boolean) false);
        f.a("gads:interstitial_ad_pool:schema", "customTargeting");
        f.a("gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
        f.a("gads:interstitial_ad_pool:max_pools", 3);
        f.a("gads:interstitial_ad_pool:max_pool_depth", 2);
        f.a("gads:interstitial_ad_pool:time_limit_sec", 1200);
        f.a("gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
        f.a("gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
        f.a("gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
        f.a("gads:interstitial_ad_pool:discard_thresholds", 0);
        f.a("gads:interstitial_ad_pool:miss_thresholds", 0);
        f.a("gads:interstitial_ad_pool:discard_asymptote");
        f.a("gads:interstitial_ad_pool:miss_asymptote");
        f.a("gads:spherical_video:vertex_shader", "");
        f.a("gads:spherical_video:fragment_shader", "");
        f.a("gads:include_local_global_rectangles", (Boolean) false);
        f.a("gads:position_watcher:throttle_ms", 200);
        f.a("gads:position_watcher:scroll_aware_throttle_ms", 33);
        f.a("gads:position_watcher:enable_scroll_aware_ads", (Boolean) false);
        f.a("gads:position_watcher:send_scroll_data", (Boolean) false);
        f.a("gads:gen204_signals:enabled", (Boolean) false);
        f.a("gads:logged_adapter_version_classes", "");
        f.a("gads:rtb_v1_1:signal_timeout_ms", 1000);
        f.a("gads:rtb_signal:enabled", (Boolean) true);
        f.a("gads:rtb_v1_1:cld:enabled", (Boolean) true);
        f.a("gads:rtb_v1_1:cld:check_regex:enabled", (Boolean) true);
        f.a("gads:rtb_logging:regex", "(?!)");
        f.a("gads:v1_1:adapter_initialization:enabled", (Boolean) true);
        f.a("gads:adapter_initialization:min_sdk_version", 15301000);
        f.a("gads:adapter_initialization:timeout", 30);
        f.a("gads:adapter_initialization:cld_timeout", 10);
        f.a("gads:initialization_csi:enabled", (Boolean) false);
        f.a("gads:initialization_csi_control:enabled", (Boolean) false);
        f.a("gads:gestures:a2:enabled", 0);
        f.a("gads:gestures:clearTd:enabled", (Boolean) false);
        f.a("gads:gestures:asig:enabled", (Boolean) false);
        f.a("gads:gestures:ans:enabled", (Boolean) false);
        f.a("gads:gestures:tos:enabled", (Boolean) false);
        f.a("gads:gestures:brt:enabled", (Boolean) true);
        f.a("gads:signal:app_permissions:disabled", (Boolean) false);
        f.a("gads:gestures:init_new_thread:enabled", (Boolean) true);
        f.a("gads:gestures:as2percentage", 0);
        f.a("gads:gestures:vdd:enabled", (Boolean) false);
        f.a("gads:native:asset_view_touch_events", (Boolean) false);
        f.a("gads:native:set_touch_listener_on_asset_views", (Boolean) true);
        f.a("gads:ais:enabled", (Boolean) false);
        f.a("gads:send_available_disk_space:enabled", (Boolean) false);
        c.a().b.add(f.a("gads:sdk_core_constants:experiment_id", (String) null));
        f.a("gads:sdk_core_constants:caps", "");
        f.a("gads:js_flags:disable_phenotype", (Boolean) false);
        f.a("gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        f.a("gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
        f.a("gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
        f.a("gads:native_video_load_timeout", 10);
        f.a("gads:omid:native_webview_load_timeout", 2000);
        f.a("gads:enable_native_media_aspect_ratio", (Boolean) true);
        f.a("gads:native:media_content_main_image:enabled", (Boolean) true);
        f.a("gads:ad_choices_content_description", "Ad Choices Icon");
        f.a("gads:enable_store_active_view_state", (Boolean) false);
        f.a("gads:enable_singleton_broadcast_receiver", (Boolean) false);
        f.a("gads:native:media_view_match_parent:enabled", (Boolean) false);
        f.a("gads:native:count_impression_for_assets", (Boolean) false);
        f.a("gads:instream_ad:enabled", (Boolean) true);
        f.a("gads:fluid_ad:use_wrap_content_height", (Boolean) false);
        f.a("gads:auto_location_for_coarse_permission", (Boolean) false);
        f.b("gads:auto_location_for_coarse_permission:experiment_id");
        f.a("gads:auto_location_timeout", 2000);
        f.b("gads:auto_location_timeout:experiment_id");
        f.a("gads:auto_location_interval", -1);
        f.b("gads:auto_location_interval:experiment_id");
        f.a("gads:rtb_v1_1:fetch_app_settings_using_cld:enabled", (Boolean) true);
        f.a("gads:get_request_signals_cld:enabled", (Boolean) false);
        f.a("gads:rtb_v1_1:use_manifest_appid_cld:enabled", (Boolean) true);
        f.a("gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
        f.a("gads:parental_controls:timeout", 2000);
        f.a("gads:cache:ad_request_timeout_millis", 250);
        f.a("gads:cache:max_concurrent_downloads", 10);
        f.a("gads:cache:javascript_timeout_millis", 5000);
        f.a("gads:cache:bind_on_foreground", (Boolean) false);
        f.a("gads:cache:bind_on_init", (Boolean) false);
        f.a("gads:cache:bind_on_request", (Boolean) false);
        f.a("gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
        f.a("gads:cache:use_cache_data_source", (Boolean) false);
        f.a("gads:cache:connection_per_read", (Boolean) false);
        f.a("gads:cache:connection_timeout", 5000);
        f.a("gads:cache:read_only_connection_timeout", 5000);
        f.a("gads:http_assets_cache:enabled", (Boolean) false);
        f.a("gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
        f.a("gads:http_assets_cache:time_out", 100);
        f.a("gads:chrome_custom_tabs_browser:enabled", (Boolean) false);
        f.a("gads:chrome_custom_tabs:disabled", (Boolean) false);
        f.a("gads:debug_hold_gesture:time_millis", 2000);
        f.a("gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
        f.a("gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
        f.a("gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
        f.a("gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
        f.a("gads:drx_debug:timeout_ms", 5000);
        f.a("gad:pixel_dp_comparision_multiplier", 1);
        f.a("gad:interstitial_for_multi_window", (Boolean) false);
        f.a("gad:interstitial_ad_stay_active_in_multi_window", (Boolean) false);
        f.a("gad:interstitial_multi_window_method", (Boolean) false);
        f.a("gad:interstitial:close_button_padding_dip", 0);
        f.a("gads:clearcut_logging:enabled", (Boolean) false);
        f.a("gads:clearcut_logging:write_to_file", (Boolean) false);
        f.a("gad:publisher_testing:force_local_request:enabled", (Boolean) true);
        f.a("gad:publisher_testing:force_local_request:enabled_list", "");
        f.a("gad:publisher_testing:force_local_request:disabled_list", "");
        f.a("gad:http_redirect_max_count:times", 8);
        f.a("gads:omid:enabled", (Boolean) true);
        f.a("gads:omid:destroy_webview_delay", (int) ImageRequest.DEFAULT_IMAGE_TIMEOUT_MS);
        f.a("gads:nonagon:banner:enabled", (Boolean) false);
        f.a("gads:nonagon:banner:ad_unit_exclusions", "(?!)");
        f.a("gads:nonagon:app_open:enabled", (Boolean) true);
        f.a("gads:app_open_beta:min_version", 99999999);
        f.a("gads:nonagon:app_open:ad_unit_exclusions", "(?!)");
        f.a("gads:nonagon:interstitial:enabled", (Boolean) false);
        f.a("gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
        f.a("gads:nonagon:rewardedvideo:enabled", (Boolean) false);
        f.a("gads:nonagon:mobile_ads_setting_manager:enabled", (Boolean) false);
        f.a("gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
        f.a("gads:nonagon:nativead:enabled", (Boolean) false);
        f.a("gads:nonagon:nativead:app_name", "(?!)");
        f.a("gads:nonagon:banner:check_dp_size", (Boolean) true);
        f.a("gads:nonagon:rewarded:load_multiple_ads", (Boolean) true);
        f.a("gads:nonagon:return_last_error_code", (Boolean) false);
        f.a("gads:nonagon:return_no_fill_error_code", (Boolean) false);
        f.a("gads:nonagon:continue_on_no_fill", (Boolean) false);
        f.a("gads:nonagon:open_not_loaded_interstitial", (Boolean) true);
        f.a("gads:nonagon:separate_timeout:enabled", (Boolean) true);
        f.a("gads:nonagon:request_timeout:seconds", 60);
        f.a("gads:nonagon:banner_recursive_renderer", (Boolean) false);
        f.a("gads:nonagon:app_stats_lock:enabled", (Boolean) false);
        f.a("gads:nonagon:app_stats_main_thread:enabled", (Boolean) false);
        f.a("gads:uri_query_to_map_bg_thread:enabled", (Boolean) false);
        f.a("gads:nonagon:active_view_gmsg_background_thread:enabled", (Boolean) true);
        f.a("gads:active_view_gmsg_separate_pool:enabled", (Boolean) true);
        f.a("gads:nonagon:service:enabled", (Boolean) true);
        f.a("gads:nonagon:dpl_cancel_destroy_webview:enabled", (Boolean) false);
        f.a("gads:signals:ad_id_info:enabled", (Boolean) false);
        f.a("gads:signals:app_index:enabled", (Boolean) false);
        f.a("gads:signals:attestation_token:enabled", (Boolean) false);
        f.a("gads:signals:cache:enabled", (Boolean) false);
        f.a("gads:signals:doritos:enabled", (Boolean) false);
        f.a("gads:signals:doritos:v1:enabled", (Boolean) false);
        f.a("gads:signals:doritos:v2:immediate:enabled", (Boolean) false);
        f.a("gads:signals:location:enabled", (Boolean) false);
        f.a("gads:signals:network_prediction:enabled", (Boolean) false);
        f.a("gads:signals:parental_control:enabled", (Boolean) false);
        f.a("gads:signals:video_decoder:enabled", (Boolean) false);
        f.a("gads:attestation_token:enabled", (Boolean) false);
        f.a("gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
        f.a("gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
        f.a("gads:adoverlay:b68684796:targeting_sdk:upper_bound", 26);
        f.a("gads:adoverlay:b68684796:sdk_int:lower_bound", 27);
        f.a("gads:adoverlay:b68684796:sdk_int:upper_bound", 26);
        int i3 = f.a;
        f.a("gads:consent:shared_preference_reading:enabled", (Boolean) true);
        f.a("gads:consent:iab_consent_info:enabled", (Boolean) true);
        f.a("gads:fc_consent:shared_preference_reading:enabled", (Boolean) true);
        f.a("gads:sp:json_string", "");
        f.a("gads:nativeads:image:sample:enabled", (Boolean) true);
        f.a("gads:nativeads:image:sample:pixels", 1048576);
        f.a("gads:nativeads:pub_image_scale_type:enabled", (Boolean) true);
        f.a("gads:offline_signaling:enabled", (Boolean) false);
        f.a("gads:offline_signaling:log_maximum", 100);
        f.a("gads:nativeads:template_signal:enabled", (Boolean) true);
        f.a("gads:nativeads:media_content_aspect_ratio:enabled", (Boolean) true);
        f.a("gads:nativeads:media_content_metadata:enabled", (Boolean) true);
        f.a("gads:ar_ads:enabled", (Boolean) false);
        f.a("gads:precache_pool:verbose_logging", (Boolean) false);
        f.a("gads:rewarded_precache_pool:count", 0);
        f.a("gads:interstitial_precache_pool:count", 0);
        f.a("gads:rewarded_precache_pool:discard_strategy", "lru");
        f.a("gads:interstitial_precache_pool:discard_strategy", "lru");
        f.a("gads:rewarded_precache_pool:cache_start_trigger", "onAdClosed");
        f.a("gads:interstitial_precache_pool:cache_start_trigger", "onAdClosed");
        f.a("gads:rewarded_precache_pool:size", 1);
        f.a("gads:interstitial_precache_pool:size", 1);
        f.a("gads:rewarded_precache_pool:ad_time_limit", 1200);
        f.a("gads:interstitial_precache_pool:ad_time_limit", 1200);
        f.a("gads:rewarded_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
        f.a("gads:interstitial_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
        f.a("gads:app_open_precache_pool:schema", "orientation,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
        f.a("gads:app_open_precache_pool:discard_strategy", "oldest");
        f.a("gads:app_open_precache_pool:count", 0);
        f.a("gads:app_open_precache_pool:cache_start_trigger", "onAdClosed");
        f.a("gads:app_open_precache_pool:size", 1);
        f.a("gads:app_open_precache_pool:ad_time_limit", 14400);
        f.a("gads:memory_leak:b129558083", (Boolean) false);
        f.a("gads:unhandled_event_reporting:enabled", (Boolean) false);
        f.a("gads:response_info:enabled", (Boolean) true);
        f.a("gads:csi:interstitial_failed_to_show:enabled", (Boolean) false);
        f.a("gads:csi:mediation_failure:enabled", (Boolean) false);
        f.a("gads:csi:error_parsing:regex", "\\d+");
        f.a("gads:signal_collection_without_rendering:enabled", (Boolean) true);
        f.a("gads:native_ads_signal:timeout", (int) ImageRequest.DEFAULT_IMAGE_TIMEOUT_MS);
        f.a("gads:signal_v2:min_version", 19677000);
        f.a("gads:paid_event_listener:enabled", (Boolean) false);
        f.a("gads:is_in_scroll_view_new_api:enabled", (Boolean) true);
        f.a("gads:wire_banner_listener_after_request:enabled", (Boolean) false);
    }

    /* JADX WARNING: type inference failed for: r0v1, types: [java.util.List, java.util.Collection] */
    public static List a() {
        g a2 = c.a();
        ArrayList arrayList = new ArrayList();
        ? r0 = a2.b;
        int size = r0.size();
        for (int i2 = 0; i2 < size; i2++) {
            String str = (String) ((f) r0.get(i2)).a();
            if (!TextUtils.isEmpty(str)) {
                arrayList.add(str);
            }
        }
        ArrayList arrayList2 = new ArrayList();
        o.a(arrayList2, a.a("gad:dynamite_module:experiment_id", ""));
        o.a(arrayList2, com.google.android.gms.ads.internal.flag.c.a);
        o.a(arrayList2, com.google.android.gms.ads.internal.flag.c.b);
        o.a(arrayList2, com.google.android.gms.ads.internal.flag.c.c);
        o.a(arrayList2, com.google.android.gms.ads.internal.flag.c.d);
        o.a(arrayList2, com.google.android.gms.ads.internal.flag.c.e);
        o.a(arrayList2, com.google.android.gms.ads.internal.flag.c.k);
        o.a(arrayList2, com.google.android.gms.ads.internal.flag.c.f);
        o.a(arrayList2, com.google.android.gms.ads.internal.flag.c.g);
        o.a(arrayList2, com.google.android.gms.ads.internal.flag.c.h);
        o.a(arrayList2, com.google.android.gms.ads.internal.flag.c.i);
        o.a(arrayList2, com.google.android.gms.ads.internal.flag.c.j);
        arrayList.addAll(arrayList2);
        return arrayList;
    }

    public static void a(Context context) {
        r.a(new m(context));
    }
}
