package defpackage;

import android.app.Application;

/* renamed from: agea  reason: default package */
/* compiled from: :com.google.android.gms@201216073@20.12.16 (080306-306753009) */
final class agea implements agft {
    private final bapu A;
    private final bapu B;
    private final bapu C;
    private final bapu D;
    private final bapu E;
    private final bapu F;
    private final bapu G;
    private final bapu H;
    private final bapu I;
    private final bapu J;
    private final bapu K;
    private final bapu L;
    private final bapu M;
    private final bapu N;
    private final bapu O;
    private final bapu P;
    private final bapu Q;
    private final bapu R;
    private final bapu S;
    private final bapu T;
    private final bapu U;
    private final bapu V;
    private final bapu W;
    private final bapu X;
    private final bapu Y;
    private final bapu Z;
    public final bapu a;
    private final bapu aa;
    private final bapu ab;
    private final bapu ac;
    private final bapu ad;
    private final bapu ae;
    private final bapu af;
    private final bapu ag;
    private final bapu ah;
    private final bapu ai;
    private final bapu aj;
    private final bapu ak;
    private final bapu al;
    private final bapu am;
    private final bapu an;
    private final bapu b;
    private final bapu c;
    private final bapu d;
    private final bapu e;
    private final bapu f = awds.a(new aggx(this.d));
    private final bapu g;
    private final bapu h;
    private final bapu i;
    private final bapu j;
    private final bapu k;
    private final bapu l;
    private final bapu m;
    private final bapu n;
    private final bapu o;
    private final bapu p;
    private final bapu q;
    private final bapu r;
    private final bapu s;
    private final bapu t;
    private final bapu u;
    private final bapu v;
    private final bapu w;
    private final bapu x;
    private final bapu y;
    private final bapu z;

    public agea(Application application, amsv amsv, amsv amsv2, aghs aghs, amsv amsv3, agit agit) {
        this.b = awdu.a(application);
        awdt a2 = awdu.a(aghs);
        this.c = a2;
        bapu a3 = awds.a(new agep(a2));
        this.d = a3;
        this.e = awds.a(new aggy(a3));
        awdt a4 = awdu.a(amsv3);
        this.g = a4;
        this.h = awds.a(new ageo(a4));
        awdt a5 = awdu.a(amsv2);
        this.i = a5;
        this.j = awds.a(new agen(a5));
        awdt a6 = awdu.a(amsv);
        this.k = a6;
        this.l = awds.a(new agib(a6));
        this.m = awds.a(new agfs(this.d));
        this.n = new agej(this.l);
        ager ager = new ager(this.l);
        this.o = ager;
        this.p = new agdq(ager);
        agem agem = new agem(this.l);
        this.q = agem;
        this.r = new agds(agem);
        ageq ageq = new ageq(this.l);
        this.s = ageq;
        this.t = new agdp(ageq);
        ageg ageg = new ageg(this.l);
        this.u = ageg;
        bapu a7 = awds.a(new agdo(this.b, ageg));
        this.v = a7;
        this.w = new agku(this.n, a7, this.h);
        agne agne = new agne(this.j);
        this.x = agne;
        this.y = new agko(agne);
        this.z = new agkq(this.b);
        aged aged = new aged(this.l);
        this.A = aged;
        agjw agjw = new agjw(this.v, this.z, aged);
        this.B = agjw;
        bapu a8 = awds.a(new agkb(this.w, this.b, this.e, this.y, agjw));
        this.C = a8;
        new agkl(a8, this.h, this.A);
        agee agee = new agee(this.l);
        this.D = agee;
        this.E = awds.a(new agdy(this.w, this.b, this.e, agee));
        ageh ageh = new ageh(this.l);
        this.F = ageh;
        bapu a9 = awds.a(new aglq(this.w, this.b, this.e, ageh));
        this.G = a9;
        new aglt(a9, this.h, this.F);
        bapu a10 = awds.a(new agli(this.w, this.b, this.F, this.e));
        this.H = a10;
        new agls(a10, this.h, this.F);
        agei agei = new agei(this.l);
        this.I = agei;
        bapu a11 = awds.a(new agmg(this.w, this.b, this.e, agei));
        this.J = a11;
        this.K = new agmi(a11, this.h, this.I);
        agek agek = new agek(this.l);
        this.L = agek;
        agex agex = new agex(agek);
        this.M = agex;
        this.N = awds.a(new agfd(this.w, this.b, this.e, this.L, agex));
        agel agel = new agel(this.l);
        this.O = agel;
        this.P = new agfj(this.w, this.b, this.e, agel, this.j);
        this.Q = new agec(this.b);
        this.R = awds.a(new agmt(this.w, this.e));
        this.S = awdu.a(agit);
        bapu a12 = awds.a(agiz.a);
        this.T = a12;
        bapu a13 = awds.a(new agiu(this.b, a12));
        this.U = a13;
        this.V = awds.a(new agix(this.S, a13));
        this.W = awds.a(new agiv(this.S, this.U));
        bapu a14 = awds.a(new agiw(this.S, this.U));
        this.X = a14;
        this.Y = new agmr(this.Q, this.R, this.V, this.W, a14, this.h);
        agdn agdn = new agdn(this.m);
        this.Z = agdn;
        this.aa = new agij(this.w, this.e, this.o, agdn);
        bapu a15 = awds.a(new agip(this.w, this.e, this.t, this.s, this.q, this.h));
        this.ab = a15;
        agim agim = new agim(this.aa, a15);
        this.ac = agim;
        this.ad = awds.a(new agdr(this.p, this.r, agim, this.aa));
        this.ae = new agkk(this.C, this.A);
        this.af = new aglu(this.G, this.H, this.F);
        agef agef = new agef(this.l);
        this.ag = agef;
        agla agla = new agla(agef, this.b);
        this.ah = agla;
        bapu a16 = awds.a(new aglb(this.w, this.b, this.e, this.ag, agla));
        this.ai = a16;
        this.aj = new aglc(this.l, a16);
        this.ak = new agmh(this.J, this.I);
        awds.a(new agnc(this.w, this.e, this.h));
        this.al = new agmw(this.ag);
        awdz a17 = awea.a(0, 5);
        a17.a(this.ae);
        a17.a(this.af);
        a17.a(this.aj);
        a17.a(this.ak);
        a17.a(this.al);
        awea a18 = a17.a();
        this.am = a18;
        bapu a19 = awds.a(new agdm(this.b, this.l, this.j, this.h, this.e, this.p, this.t, this.E, this.K, this.N, this.P, this.Y, this.ad, this.ab, a18));
        this.an = a19;
        this.a = new aggf(this.b, this.e, this.f, this.h, this.j, this.l, this.d, this.m, a19);
    }
}
