package defpackage;

import android.os.Build;

/* renamed from: et  reason: default package */
/* compiled from: :com.google.android.gms@201216073@20.12.16 (080306-306753009) */
public final class et {
    public int A = -1;
    public int B = -1;
    public int C = -1;
    public int D = -1;
    public int E = -1;
    public int F = -1;
    public int G = 0;
    public int H = -1;
    public int I = -1;
    public int J = -1;
    public int K = -1;
    public int L = -1;
    public int M = -1;
    public float N = 0.0f;
    public float O = 0.0f;
    public int P = 0;
    public int Q = 0;
    public float R = 1.0f;
    public boolean S = false;
    public float T = 0.0f;
    public float U = 0.0f;
    public float V = 0.0f;
    public float W = 1.0f;
    public float X = 1.0f;
    public float Y = 0.0f;
    public float Z = 0.0f;
    public boolean a = false;
    public float aa = 0.0f;
    public float ab = 0.0f;
    public float ac = 0.0f;
    public int ad = -1;
    public int ae = -1;
    public int af = -1;
    public int ag = -1;
    public int ah = -1;
    public int ai = -1;
    public int b;
    public int c;
    int d;
    public int e = -1;
    public int f = -1;
    public float g = -1.0f;
    public int h = -1;
    public int i = -1;
    public int j = -1;
    public int k = -1;
    public int l = -1;
    public int m = -1;
    public int n = -1;
    public int o = -1;
    public int p = -1;
    public int q = -1;
    public int r = -1;
    public int s = -1;
    public int t = -1;
    public float u = 0.5f;
    public float v = 0.5f;
    public String w = null;
    public int x = -1;
    public int y = -1;
    public int z = -1;

    public final void a(es esVar) {
        esVar.d = this.h;
        esVar.e = this.i;
        esVar.f = this.j;
        esVar.g = this.k;
        esVar.h = this.l;
        esVar.i = this.m;
        esVar.j = this.n;
        esVar.k = this.o;
        esVar.l = this.p;
        esVar.m = this.q;
        esVar.n = this.r;
        esVar.o = this.s;
        esVar.p = this.t;
        esVar.leftMargin = this.A;
        esVar.rightMargin = this.B;
        esVar.topMargin = this.C;
        esVar.bottomMargin = this.D;
        esVar.u = this.M;
        esVar.v = this.L;
        esVar.w = this.u;
        esVar.x = this.v;
        esVar.y = this.w;
        esVar.K = this.x;
        esVar.L = this.y;
        esVar.B = this.N;
        esVar.A = this.O;
        esVar.D = this.Q;
        esVar.C = this.P;
        esVar.E = this.ad;
        esVar.F = this.ae;
        esVar.I = this.af;
        esVar.J = this.ag;
        esVar.G = this.ah;
        esVar.H = this.ai;
        esVar.M = this.z;
        esVar.c = this.g;
        esVar.a = this.e;
        esVar.b = this.f;
        esVar.width = this.b;
        esVar.height = this.c;
        int i2 = Build.VERSION.SDK_INT;
        esVar.setMarginStart(this.F);
        esVar.setMarginEnd(this.E);
        esVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        et etVar = new et();
        etVar.a = this.a;
        etVar.b = this.b;
        etVar.c = this.c;
        etVar.e = this.e;
        etVar.f = this.f;
        etVar.g = this.g;
        etVar.h = this.h;
        etVar.i = this.i;
        etVar.j = this.j;
        etVar.k = this.k;
        etVar.l = this.l;
        etVar.m = this.m;
        etVar.n = this.n;
        etVar.o = this.o;
        etVar.p = this.p;
        etVar.q = this.q;
        etVar.r = this.r;
        etVar.s = this.s;
        etVar.t = this.t;
        etVar.u = this.u;
        etVar.v = this.v;
        etVar.w = this.w;
        etVar.x = this.x;
        etVar.y = this.y;
        etVar.u = this.u;
        etVar.u = this.u;
        etVar.u = this.u;
        etVar.u = this.u;
        etVar.u = this.u;
        etVar.z = this.z;
        etVar.A = this.A;
        etVar.B = this.B;
        etVar.C = this.C;
        etVar.D = this.D;
        etVar.E = this.E;
        etVar.F = this.F;
        etVar.G = this.G;
        etVar.H = this.H;
        etVar.I = this.I;
        etVar.J = this.J;
        etVar.K = this.K;
        etVar.L = this.L;
        etVar.M = this.M;
        etVar.N = this.N;
        etVar.O = this.O;
        etVar.P = this.P;
        etVar.Q = this.Q;
        etVar.R = this.R;
        etVar.S = this.S;
        etVar.T = this.T;
        etVar.U = this.U;
        etVar.V = this.V;
        etVar.W = this.W;
        etVar.X = this.X;
        etVar.Y = this.Y;
        etVar.Z = this.Z;
        etVar.aa = this.aa;
        etVar.ab = this.ab;
        etVar.ac = this.ac;
        etVar.ad = this.ad;
        etVar.ae = this.ae;
        etVar.af = this.af;
        etVar.ag = this.ag;
        etVar.ah = this.ah;
        etVar.ai = this.ai;
        return etVar;
    }
}
