package defpackage;

/* renamed from: ozl  reason: default package */
/* compiled from: :com.google.android.gms@201216073@20.12.16 (080306-306753009) */
enum ozl {
    OK,
    NO_UNIVERSAL_SECTION_MAPPING,
    FILTERED_BY_SPEC,
    NOT_OMNIBOX_CORPUS_IN_CHROME_OMNIBOX,
    NOT_AUTHORIZED_FOR_INTERNAL_CORPUS,
    PACKAGE_NOT_GLOBALLY_SEARCHABLE,
    CONTENT_CORPUS_NOT_ENABLED,
    CLIENT_NOT_EXIST,
    SETTINGS_USER_DISABLED
}
